services:
    app:
        build: .
        container_name: larablade-app
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
        networks:
            - laravel-network
    web:
        image: 'nginx:alpine'
        container_name: larablade-web
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
            - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - app
        networks:
            - laravel-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: larablade-phpmyadmin
        restart: unless-stopped
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: laravel
            PMA_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - laravel-network
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: larablade-database
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - laravel-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: larablade-cache
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - laravel-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
volumes:
    db_data: null
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
networks:
    laravel-network:
        driver: bridge
